### ISSUE TITLE
Error: 'Options' object has no attribute 'service' with oracle connection

### ISSUE THREAD

**Issue by maialithar** [jum4/sublime-sqlexec#32]
I have configured plugin like that in user settings):

```
{
    "sql_exec.commands": {
        "oracle" : "sqlplus"
    }, 
    "connections": {
        "name": {
            "type": "oracle",
            "host": "hostnamee",
            "port": port_number,
            "username": "user",
            "password": "pass",
            "database": "sid",
            "service": "sid"
        }
    }
}
```

But when I try to run any query (`select sysdate from dual;`) I get this in output window:

```
Traceback (most recent call last):
  File "SQLExec in C:\[path]\Sublime Text 3\Installed Packages\SQLExec.sublime-package", line 172, in executeQuery
  File "SQLExec in C:\[path]\Sublime Text 3\Installed Packages\SQLExec.sublime-package", line 29, in execute
  File "SQLExec in C:\[path]\Sublime Text 3\Installed Packages\SQLExec.sublime-package", line 16, in _getCommand
  File "SQLExec in C:\[path]\Sublime Text 3\Installed Packages\SQLExec.sublime-package", line 13, in _buildCommand
AttributeError: 'Options' object has no attribute 'service'
```

Any help would be much appreciated!

**Comment by Carpette** [comment]
Exact same problem here, i'd like to know if you've find something to passby this issue

**Comment by meganlkm** [comment]
I had to edit the `args` property in the sgbd/oracle.sqlexec file. This is what I changed it to:

```
"args": "{options.username}/{options.password}@{options.host}:{options.port}/{options.service}"
```
